version: 2
sources:
  - name: raw_data
    database: dbt 
    schema: raw_data 
    tables:
      - name: employee
        columns:
         - name: empid
           tests:
           - unique
           - not_null
      - name: customers    